# -*- coding: utf-8 -*-
"""mimic_cxr_fft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flnegwsCA-NXz_0R1t5o37Jb3P-ruNZ_

## Dataset Class
"""

from google.colab import drive
from google.colab import auth
from google.cloud import storage

auth.authenticate_user()